Improve availability of library
GeoWerkstatt/geow-interlis-functions pull request #10
Opened 2022-01-27 14:08 UTC by Philippluca

Resolves #5
Resolves #6

2022-01-28 09:28 UTC, patrickackermann requested changes

2022-01-28 09:28 UTC, patrickackermann commented on Readme.md
> +- Es muss sichergestellt werden, dass der ilivalidator das Modell in einem Repository finden kann. Hier kann GitHub direkt z.B. direkt Eingebunden werden.
REQ: Hier hat es ein _direkt_ zuviel, oder sonstwie umformulieren.
```suggestion
- Es muss sichergestellt werden, dass der ilivalidator das Modell in einem Repository finden kann. Hier kann GitHub z.B. direkt Eingebunden werden. 
```

2022-01-28 09:42 UTC, flenny requested changes

2022-01-28 09:42 UTC, flenny commented on Readme.md
> +- **Jar-File:** Die Funktionsbibliothek (.jar-File) kann von GitHub aus dem [aktuellsten Release](https://github.com/GeoWerkstatt/geow-interlis-functions/releases) heruntergeladen werden. Das .jar-Fi
PP:

```suggestion
- **Jar-File:** Die Funktionsbibliothek (.jar-File) kann von GitHub aus dem [aktuellsten Release](https://github.com/GeoWerkstatt/geow-interlis-functions/releases/latest) heruntergeladen werden. Das .jar-File muss dem _ilivalidator_ bekannt gemacht werden.
```

2022-01-28 09:42 UTC, flenny commented on Readme.md
> +- Es muss sichergestellt werden, dass der ilivalidator das Modell in einem Repository finden kann. Hier kann GitHub direkt z.B. direkt Eingebunden werden.
REQ: _Eingebunden_ -> _eingebunden_

2022-01-28 09:42 UTC, flenny commented on .github/workflows/release.yml
>      - uses: ncipollo/release-action@v1
PP: Release Action auf expliziten Commit pinnen, da es sich um eine _inoffizielle_ Action handelt (Sicherheitsüberlegungen). Siehe [hier](https://github.com/GeoWerkstatt/interlis-check-service/blob/main/.github/workflows/pre-release.yml#L61).

2022-02-09 07:07 UTC, flenny approved these changes

2022-02-09 07:47 UTC, merged