Add Union function
GeoWerkstatt/geow-interlis-functions pull request #35
Opened 2023-12-14 08:41 UTC by domi-b

Resolves #33

2023-12-14 14:28 UTC, patrickackermann requested changes

2023-12-14 14:28 UTC, patrickackermann commented on src/main/java/ch/geowerkstatt/ilivalidator/extensions/functions/UnionIoxPlugin.java
> +            return Objects.equals(surfaces, that.surfaces);
Ich bin mir nicht sicher, ob der cache sinn macht. `IomObject` bzw. die implementierung des interfaces `Iom_jObject` überschreibt übrigens equals nicht.

2023-12-14 15:00 UTC, domi-b commented on src/main/java/ch/geowerkstatt/ilivalidator/extensions/functions/EvaluationHelper.java
> +    public static IomObject jts2multiSurface(MultiPolygon multiPolygon) throws Iox2jtsException {
In `Jtsext2iox` gibt nur eine Funktion `JTS2surface`, die ich hier auch verwende. Für multisurfaces gibt es leider noch keine Funktion.

2023-12-14 15:03 UTC, domi-b commented on src/test/data/GetInnerRingsCount/TestData.xtf
> -                                        <geom:c3>467</geom:c3>
Nach dem Update von ili2c und iox-ili gibt es neu einen Fehler, wenn die Daten weitere Dimensionen haben (die Koordinaten haben im Modell nur 2 Dimensionen).

2023-12-14 15:09 UTC, patrickackermann commented on src/main/java/ch/geowerkstatt/ilivalidator/extensions/functions/EvaluationHelper.java
> +    public static IomObject jts2multiSurface(MultiPolygon multiPolygon) throws Iox2jtsException {
Habe mich vertippt, ich habe diese Funktion in `Jts2iox` gemeint: https://github.com/claeis/iox-ili/blob/96eaab1d6853927b621140cd445efa523666f8c9/src/main/java/ch/interlis/iox_j/jts/Jts2iox.java#L225

2023-12-14 15:25 UTC, domi-b commented on src/model/GeoW_FunctionsExt.ili
> +    FUNCTION Union (Objects: OBJECTS OF ANYCLASS; AreaAttr: TEXT): OBJECT OF ANYCLASS;
RefHB 2.12:
> Konsistenzbedingungen, die sich auf ein einzelnes Objekt beziehen, werden durch einen logischen Ausdruck beschrieben, der sich auf die Attribute des Objektes bezieht (s. nächstes Kapitel). Solche Bedingungen dürfen keine Funktion verwenden, die auf einem Argument (typischerweise auf dem ersten) eine Menge von Objekten (OBJECTS OF) erwartet.

Diese Einschränkung macht meiner Meinung nach keinen Sinn, wenn über ein Objekt-Pfad navigiert wird, der eine Menge von Objekten ergibt (Association mit Kardinalität > 1 oder Attribut mit Typ `LIST OF` oder `BAG OF`), oder verstehe ich da etwas falsch?

2023-12-14 15:42 UTC, domi-b commented on src/main/java/ch/geowerkstatt/ilivalidator/extensions/functions/UnionIoxPlugin.java
> +            return Objects.equals(surfaces, that.surfaces);
Fürs equals vom `UnionSurfaceKey` wird das equals der `surfaces` (Typ `Collection`) verwendet. Dieses prüft, dass die einzelnen Elemente innerhalb der Collection gleich sind.
Da die `IomObject`s wiederverwendet und nicht kopiert werden, reicht es hier zu prüfen, dass es noch die gleichen Objekte sind mit der Default-Implementation von equals.

2023-12-14 16:04 UTC, patrickackermann commented on src/model/GeoW_FunctionsExt.ili
> +    FUNCTION Union (Objects: OBJECTS OF ANYCLASS; AreaAttr: TEXT): OBJECT OF ANYCLASS;
Ich habe es bisher so gedeutet, dass bei `OBJECTS` ausschliesslich `ALL` oder eine expression, die zu mehreren objekten evaluieren kann gültig ist und kein Pfad. Das über einen Pfad über Associations mehrere Objekte angesprochen werden können war mir anfangs aber auch noch nicht bewusst.🤷

Das Resultat dieser Einschränkung ist jedenfalls, dass es z.B. von den AreAreas funktionen jeweils mehrere varianten gibt, einmal mit `OBJECT` und einmal mit `OBJECTS`. Der Compiler jedenfalls schert sich soweit ich weiss nicht um die typen bei Funktionsaufrufen.

2023-12-18 07:54 UTC, domi-b commented on src/model/GeoW_FunctionsExt.ili
> +    FUNCTION Union (Objects: OBJECTS OF ANYCLASS; AreaAttr: TEXT): OBJECT OF ANYCLASS;
Das könnte bedeuten, dass für `OBJECTS OF ANYCLASS` nur `ALL` und für `OBJECT OF ANYCLASS` nur `THIS` übergeben werden soll?
Ich bin davon ausgegangen, dass die Typen der Argumente geprüft werden, aber der Compiler prüft die Typen tatsächlich nicht. Aufgrund der Funktion `FUNCTION elementCount (bag: BAG OF ANYSTRUCTURE): NUMERIC;` würde ich Union jetzt so anpassen: `FUNCTION Union (Geometries: BAG OF ANYSTRUCTURE): ANYSTRUCTURE;`, denn `SURFACE` ist eine Structure und kein Objekt.

2023-12-18 14:11 UTC, patrickackermann approved these changes

2023-12-18 14:16 UTC, merged