Add PolylinesNotOverlapping function
GeoWerkstatt/geow-interlis-functions pull request #36
Opened 2023-12-19 09:14 UTC by domi-b

Resolves #32

2023-12-19 13:13 UTC, patrickackermann requested changes

2023-12-19 13:13 UTC, patrickackermann commented on src/test/java/ch/geowerkstatt/ilivalidator/extensions/functions/PolylinesNotOverlappingIoxPluginTest.java
> +public final class PolylinesNotOverlappingIoxPluginTest {
Q: Wie ist das Verhalten bei zwei identischen Linien, wird das getestet?

2023-12-19 13:13 UTC, patrickackermann commented on src/main/java/ch/geowerkstatt/ilivalidator/extensions/functions/PolylinesNotOverlappingIoxPlugin.java
> +                if (lines.get(i).overlaps(lines.get(j))) {
PP: Der Overlaps test ist möglicherweise etwas zeitaufwändig. Mithilfe eines STRtree könnten effizient nur noch jene Linien auf Overlaps überprüft werden, deren BoundingBox/Envelope überlappt.

2023-12-20 10:46 UTC, domi-b commented on src/test/java/ch/geowerkstatt/ilivalidator/extensions/functions/PolylinesNotOverlappingIoxPluginTest.java
> +public final class PolylinesNotOverlappingIoxPluginTest {
Ich habe das Verhalten noch etwas angepasst, dass Linien mit gleichen Teilstrecken nun auch als Overlap gelten (es entspricht somit nicht mehr zu 100% der Definition von overlap, aber ich habe keinen passenderen Begriff gefunden).
Dabei wird geprüft, dass die Schnittmenge der Linien ebenfalls eine Linie ist (entspricht den Beispielen 29-47 im folgenden Bild).

![DE-9IM von Linien](https://onlinelibrary.wiley.com/cms/asset/22450c38-3698-4f48-bd9e-86c24819356a/tgis12328-fig-0004-m.jpg)

2023-12-20 10:52 UTC, domi-b commented on src/main/java/ch/geowerkstatt/ilivalidator/extensions/functions/PolylinesOverlapIoxPlugin.java
> +        boolean hasOverlap = HAS_EQUAL_LINE_PART_CACHE.computeIfAbsent(key, k -> {
Ich hatte noch vergessen, die Resultate zu cachen.
Macht es Sinn, dass für den Cache die Objekt-Ids und der Attributpfad verwendet werden?
Die übliche Verwendung ist vermutlich in einem Set-Constraint mit `GeoW_FunctionsExt.PolylinesOverlap(ALL, 'Geometrie');`, da sollten alle Objekte eine Id haben.

2023-12-20 14:02 UTC, patrickackermann requested changes

2023-12-20 15:16 UTC, patrickackermann approved these changes

2023-12-20 15:35 UTC, merged